### ISSUE TITLE
Store Crypto (ecurrency) info on IPFS

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-block-explorer-IPFS#6]
The wallet needs to provide about/info/overview info for the supported currencies.

For each crypto currency that supported by our BANK wallet we would like to have an overview information about the asset/coin and any other information about the project.

The info will consists of several sections and in initial implementation will have a structure similar to the one below.

ABOUT
- token concept explained
- team(s) behind the project
- relevant Youtube videos if any

TOKEN
- token symbol 
- token current price in base currency
- number of coins total
- number of coins in circulation 

ADOPTION
- users
- developers

Use some dummy data for the first implementation. the actual data for all supported currencies will be added once the implementation is in place.

**Comment by nk-the-crazy** [comment]
Currency rates are stored in IPFS, using unix directory structure
(IPFS/source_currency/target_currency/YY/MM/HH/MM/index.json) with period of ~2-3 minutes.
